name: Deploy Credential Validator Lambda (OIDC)

on:
  push:
    branches: [ main, master ]
    paths:
      - 'src/credential-validator/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'src/credential-validator/**'
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  NODE_VERSION: '22'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies
      run: |
        cd src/credential-validator
        npm ci

    - name: Build
      run: |
        cd src/credential-validator
        npm run build

    - name: Run tests
      run: |
        cd src/credential-validator
        npm test -- --passWithNoTests

  deploy-credential-validator:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies
      run: |
        cd src/credential-validator
        npm ci

    - name: Build
      run: |
        cd src/credential-validator
        npm run build

    - name: Create deployment package
      run: |
        cd src/credential-validator
        mkdir -p deployment
        cp -r build/* deployment/
        cp package.json deployment/
        cd deployment
        npm install --production
        zip -r credential-validator-lambda.zip .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy to Lambda
      run: |
        cd src/credential-validator/deployment
        aws lambda update-function-code \
          --function-name peptide-tracker-credential-validator-dev \
          --zip-file fileb://credential-validator-lambda.zip \
          --region ${{ env.AWS_REGION }} || \
        aws lambda create-function \
          --function-name peptide-tracker-credential-validator-dev \
          --runtime nodejs22.x \
          --role ${{ secrets.AWS_LAMBDA_ROLE_ARN }} \
          --handler index.handler \
          --zip-file fileb://credential-validator-lambda.zip \
          --region ${{ env.AWS_REGION }}

    - name: Cleanup
      run: |
        cd src/credential-validator
        rm -rf deployment
